export const categories = [
  {
    name: "HTML",
    materials: [
      {
        id: 1,
        materi: "Dasar HTML",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 100,
      },
      {
        id: 2,
        materi: "HTML Forms",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 80,
      },
      {
        id: 3,
        materi: "HTML5 Features",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 90,
      },
      {
        id: 4,
        materi: "Semantic HTML",
        jumlah_modul: 3,
        waktu: 40,
        jumlah_siswa: 70,
      },
      {
        id: 5,
        materi: "HTML Best Practices",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 85,
      },
      {
        id: 6,
        materi: "HTML Accessibility",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 75,
      },
    ],
  },
  {
    name: "CSS",
    materials: [
      {
        id: 1,
        materi: "CSS Fundamentals",
        jumlah_modul: 6,
        waktu: 70,
        jumlah_siswa: 110,
      },
      {
        id: 2,
        materi: "CSS Layouts",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 95,
      },
      {
        id: 3,
        materi: "CSS Animations",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 85,
      },
      {
        id: 4,
        materi: "Responsive Design",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 105,
      },
      {
        id: 5,
        materi: "CSS Preprocessors",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 90,
      },
      {
        id: 6,
        materi: "CSS Grid",
        jumlah_modul: 3,
        waktu: 40,
        jumlah_siswa: 80,
      },
    ],
  },
  {
    name: "Tailwind CSS",
    materials: [
      {
        id: 1,
        materi: "Tailwind Basics",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 100,
      },
      {
        id: 2,
        materi: "Tailwind Components",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 90,
      },
      {
        id: 3,
        materi: "Tailwind Customization",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 80,
      },
      {
        id: 4,
        materi: "Tailwind Utilities",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 95,
      },
      {
        id: 5,
        materi: "Tailwind in Production",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 105,
      },
      {
        id: 6,
        materi: "Tailwind with React",
        jumlah_modul: 4,
        waktu: 60,
        jumlah_siswa: 85,
      },
    ],
  },
  {
    name: "Bootstrap",
    materials: [
      {
        id: 1,
        materi: "Bootstrap Basics",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 100,
      },
      {
        id: 2,
        materi: "Bootstrap Grid System",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 85,
      },
      {
        id: 3,
        materi: "Bootstrap Components",
        jumlah_modul: 6,
        waktu: 70,
        jumlah_siswa: 110,
      },
      {
        id: 4,
        materi: "Bootstrap Utilities",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 90,
      },
      {
        id: 5,
        materi: "Customizing Bootstrap",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 80,
      },
      {
        id: 6,
        materi: "Bootstrap with JavaScript",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 95,
      },
    ],
  },
  {
    name: "JavaScript",
    materials: [
      {
        id: 1,
        materi: "JS Fundamentals",
        jumlah_modul: 7,
        waktu: 80,
        jumlah_siswa: 120,
      },
      {
        id: 2,
        materi: "DOM Manipulation",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 105,
      },
      {
        id: 3,
        materi: "Async JavaScript",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 95,
      },
      {
        id: 4,
        materi: "ES6+ Features",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 100,
      },
      {
        id: 5,
        materi: "JavaScript OOP",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 90,
      },
      {
        id: 6,
        materi: "JavaScript Design Patterns",
        jumlah_modul: 6,
        waktu: 70,
        jumlah_siswa: 85,
      },
    ],
  },
  {
    name: "React.js",
    materials: [
      {
        id: 1,
        materi: "React Basics",
        jumlah_modul: 6,
        waktu: 70,
        jumlah_siswa: 110,
      },
      {
        id: 2,
        materi: "React Hooks",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 100,
      },
      {
        id: 3,
        materi: "React Router",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 90,
      },
      {
        id: 4,
        materi: "State Management",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 105,
      },
      {
        id: 5,
        materi: "React Testing",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 85,
      },
      {
        id: 6,
        materi: "React Performance",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 80,
      },
    ],
  },
  {
    name: "Next.js",
    materials: [
      {
        id: 1,
        materi: "Next.js Fundamentals",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 100,
      },
      {
        id: 2,
        materi: "Routing in Next.js",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 90,
      },
      {
        id: 3,
        materi: "API Routes",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 85,
      },
      {
        id: 4,
        materi: "SSR and SSG",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 95,
      },
      {
        id: 5,
        materi: "Next.js with TypeScript",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 80,
      },
      {
        id: 6,
        materi: "Deploying Next.js Apps",
        jumlah_modul: 3,
        waktu: 40,
        jumlah_siswa: 75,
      },
    ],
  },
  {
    name: "PHP",
    materials: [
      {
        id: 1,
        materi: "PHP Basics",
        jumlah_modul: 6,
        waktu: 70,
        jumlah_siswa: 110,
      },
      {
        id: 2,
        materi: "PHP OOP",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 100,
      },
      {
        id: 3,
        materi: "PHP and MySQL",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 95,
      },
      {
        id: 4,
        materi: "PHP Security",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 90,
      },
      {
        id: 5,
        materi: "PHP APIs",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 85,
      },
      {
        id: 6,
        materi: "PHP Design Patterns",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 80,
      },
    ],
  },
  {
    name: "Laravel",
    materials: [
      {
        id: 1,
        materi: "Laravel Basics",
        jumlah_modul: 7,
        waktu: 80,
        jumlah_siswa: 120,
      },
      {
        id: 2,
        materi: "Eloquent ORM",
        jumlah_modul: 5,
        waktu: 65,
        jumlah_siswa: 110,
      },
      {
        id: 3,
        materi: "Laravel Authentication",
        jumlah_modul: 4,
        waktu: 55,
        jumlah_siswa: 100,
      },
      {
        id: 4,
        materi: "Laravel API Development",
        jumlah_modul: 5,
        waktu: 60,
        jumlah_siswa: 95,
      },
      {
        id: 5,
        materi: "Laravel Testing",
        jumlah_modul: 4,
        waktu: 50,
        jumlah_siswa: 90,
      },
      {
        id: 6,
        materi: "Laravel Deployment",
        jumlah_modul: 3,
        waktu: 45,
        jumlah_siswa: 85,
      },
    ],
  },
];
